/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/app-header.vue')['default']
    AppHeaderNav: typeof import('./src/components/app-header-nav.vue')['default']
    AppHeaderSticky: typeof import('./src/components/app-header-sticky.vue')['default']
    AppPage: typeof import('./src/components/app-page.vue')['default']
    AppTopNav: typeof import('./src/components/app-top-nav.vue')['default']
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
